[[pages]]
path = "./syn_app/Introduction.py"
name = "Introduction"
icon = "ğŸ“„"

[[pages]]
name = "Synonymous mutations in COSMIC v98"
icon = "ğŸ‘¤"
is_section = true

[[pages]]
path = "./syn_app/mutation_selection_by_chroms.py"
name = "By chromosomes"
icon = "ğŸ§¬"

[[pages]]
path = "./syn_app/mutation_selection_by_genes.py"
name = "By genes"
icon = "ğŸ§¬"

[[pages]]
path = "./syn_app/mutation_selection_by_recurrents.py"
name = "By sample counts"
icon = "ğŸ§¬"

[[pages]]
path = "./syn_app/mutation_selection_by_primary_sites.py"
name = "By primary sites"
icon = "ğŸ§¬"

[[pages]]
name = "Cancer driver synonymous mutation predictors"
icon = "ğŸ—ƒï¸"
is_section = true

[[pages]]
name = 'Training data'
path = "./syn_app/trainingdata_5methods.py"
icon = "ğŸ§¾"
url_path = 'trainingdata'

[[pages]]
path = "./syn_app/predictions_5methods.py"
name = "Predictions"
icon = "ğŸ§¾"
url_path = "predictions"
